services:
  cloudflared-pg-replication:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-pg-replication
    restart: unless-stopped
    networks:
      - supabase_default
    command: access tcp --hostname ${CF_PG_HOSTNAME} --url 0.0.0.0:${CF_PG_PORT}

networks:
  supabase_default:
    external: true
